config/routes.rb
Drafter::Application.routes.draw do
resources :user_sessions
resources :users do
  get 'profile'
end
resources :posts

root :to => 'posts#index'

post 'comment_create' => 'posts#comment_create', :as => :comment_create

get 'account' => 'users#account' , :as => :account
patch 'update_names' => 'users#update_names', :as => :update_names

get 'password' => 'users#password' , :as => :password
patch 'update_password' => 'users#update_password', :as => :update_password

get 'login' => 'user_sessions#new', :as => :login
post 'logout' => 'user_sessions#destroy', :as => :logout

end

app/models/comment.rb
class Comment < ActiveRecord::Base

belongs_to :user
belongs_to :post

end

app/models/post.rb
class Post < ActiveRecord::Base


  validates :title, length: { minimum: 3 }
  validates :title, uniqueness: true
  validates :description, length: { minimum: 0 }
  validates :content, presence: true

  has_many :comments
  belongs_to :user

end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!

  validates :password, length: { minimum: 8 }, on: :create
  validates :password, confirmation: true, on: :create
  validates :password_confirmation, presence: true, on: :create

  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :email, uniqueness: true, :format => { :with => email_regex }
  validates :login, uniqueness: true, length: { minimum: 3 }

  has_many :posts
  has_many :comments

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :require_login
private
def not_authenticated
  redirect_to login_path, alert: "Please login first"
end
end

app/controllers/commets_controller.rb
class CommetsController < ApplicationController
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  skip_before_filter :require_login, only: [:index, :show]

  def index
  	@posts = Post.all
  end
  
  def show
  	@post = Post.find(params[:id])
    @comments = @post.comments.joins(:user)
  end

  def new
  	@post = Post.new
  end

  def create
    @change_params = post_params
    @change_params[:user_id] = current_user.id
    source = create_source(@change_params[:content], @change_params[:user_id])
    source_name = ("user_" + @change_params[:user_id].to_s + "_" +Time.now.to_s + "." + source.format).delete(" ")
    @change_params[:content] = source_name
  	@post = Post.new @change_params
    if @post.save
      source.write(Rails.root.join("public/users/" + @change_params[:user_id].to_s + "/" + source_name))
      redirect_to root_url
    else
      render action: 'new'
    end
  end

  def destroy
  end

  def comment_create
    @comment_params = comment_params
    @comment_params[:user_id] = current_user.id
    @comment = Comment.new @comment_params
    if @comment.save
      redirect_to post_path(:id => @comment_params[:post_id])
    else
      render action: 'new'
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:post_id, :content)
  end

  def post_params
    params.require(:post).permit(:title, :description, :content)
  end
  
  def create_source(picture, user_id)
    user_path = Rails.root.join("public/users/" + user_id.to_s + "/")
    File.open(user_path + picture.original_filename, 'wb') do |file|
       file.write(picture.read)
    end
    source = Magick::Image.read(user_path + picture.original_filename).first
    File.delete(user_path + picture.original_filename)
    source.resize_to_fit!(500)
  end

end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
 skip_before_filter :require_login, except: [:destroy]
  def new
  end

  def create
    if @user = login(params[:email], params[:password])
      redirect_back_or_to(root_url)
    else
      flash.now[:alert] = "Login failed"
      render action: "new"
    end
  end

  def destroy
    logout
    redirect_to(root_url)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	skip_before_filter :require_login, only: [:new, :create]
  before_filter :find_user, only: [:profile, :account, :update_names, :password, :update_password]

  def new
  	@user = User.new
  end

  def make_user_dir(id)
    path = id.to_s
    dir_path =  Rails.root.join("public/users/")
    Dir.mkdir(dir_path + path)
    FileUtils.cp_r(dir_path + 'default_avatar.png', dir_path + path)
  end

  def create
  	@user = User.new(user_params)
    @user.avatar = "default_avatar.png"
    @user.gender = "1"
	  if @user.save
      make_user_dir(@user.id)
	    redirect_to root_url
	  else
	    render :new
	  end
  end

  def profile  
  end

  def account
  end

  def update_names
    @change_params  = update_names_params
    if @change_params[:avatar] != nil
      source = create_source(@change_params[:avatar], current_user.id.to_s)
      source_name = ("user_" + current_user.id.to_s + "_avatar." + source.format).delete(" ")
      @change_params[:avatar] = source_name
    end
    if @user.update @change_params
      if @change_params[:avatar] != nil
        source.write(Rails.root.join("public/users/" + current_user.id.to_s + "/" + source_name))
      end
      redirect_to account_path, :flash => { :success => "Дані успішно оновлено!"}
    else
      redirect_to account_path, :flash => { :alert => "Збій при оновленні!"}
    end
  end

  def create_source(picture, user_id)
    user_path = Rails.root.join("public/users/" + user_id + "/")
    File.open(user_path + picture.original_filename, 'wb') do |file|
       file.write(picture.read)
    end
    source = Magick::Image.read(user_path + picture.original_filename).first
    File.delete(user_path + picture.original_filename)
    source.resize_to_fit!(120)
  end

  def password
  end

  def update_password
    @check_data = update_password_params
    if @check_data[:password].length > 7 && @check_data[:password] == @check_data[:password_confirmation]
        if @user.update @check_data
          redirect_to password_path, :flash => { :success => "Дані успішно оновлено!"}
        else
          redirect_to password_path, :flash => { :alert => "Збій при оновленні!"}
        end
    else
      redirect_to password_path, :flash => { :alert => "Кароткий пароль, або поля не співпадають!"}
    end
  end


 private

  def find_user
    @user = current_user
  end

  def update_password_params
    params.require(:user).permit(:password, :password_confirmation)
  end

  def update_names_params
    params.require(:user).permit(:email, :login, :avatar, :gender)
  end

  def user_params
    params.require(:user).permit(:login, :email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/commets_helper.rb
module CommetsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
	def add_comment
      @comment = Comment.new
	end
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Drafter</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= posts_path %>">Drafter</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Гаряче</a></li>
        <li><a href="#">Свіже</a></li>
        <li><a href="#">Найкраще</a></li>
      </ul>
     
      <ul class="nav navbar-nav navbar-right">
         <form class="navbar-form navbar-left">
            <a class="btn btn-primary" href="<%= new_post_path %>"> Додати </a>
         </form>
        <%if current_user %>
	         <li class="dropdown">
	          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.login %><b class="caret"></b></a>
	          <ul class="dropdown-menu">
	            <li><a href="<%= user_profile_path current_user%>">Мій профайл</a></li>
	            <li><a href="<%= account_path %>">Налаштування</a></li>
	            <li class="divider"></li>
	            <li><%= link_to "Вийти", :logout, method: :post %></li>
	          </ul>
	        </li>
        <% else %>
        <li><a href="<%= login_path %>">Увійти</a></li>
        <li><a href="<%= new_user_path %>">Реєстрація</a></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>


<%= yield %>

</body>
</html>

app/views/posts/_comment_new.html.erb
 <%= form_for add_comment, :url => comment_create_path do |f| %>
    <div class="input-group">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title"> <%= f.label "Додати комментар" %> </h3>
          </div>
          <div class="panel-body">
                 <div class="field">
        		    <%= f.text_area :content, class: "form-control" %>
        		    <%= f.hidden_field :post_id, value: @post.id %>
                    <%= f.hidden_field :answer, value: "1" %>
                 </div>
                 <div class="actions">
                   <%= f.submit "Додати", class: "btn btn-primary" %>
                </div>
          </div>
        </div>
    </div>      
<% end %>

app/views/posts/index.html.erb
<div class="content_all">
  <% @posts.each do |post| %>
    <div class="row">
        <div class="col-md-2">
          <div class="rate">
            <button type="button" class="btn btn-default">Default</button>
            <button type="button" class="btn btn-default">Default</button>
          </div>
        </div>
        <div class="col-md-10">
              <div class="row">
                <div class="col-md-10">
                  <h3><%= link_to post.title, post_path(post)%></h3>
                  <div class="post_description">
                    <h5><%= post.description%></h5>
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-md-10">
                  <h4><%= image_tag("/users/" + post.user_id.to_s + "/" + post.content, :alt => "meme") %></h4>
                </div>
              </div>
        </div>
    </div>
  <% end %>  
</div>

app/views/posts/new.html.erb
<div class="new_post_content">

<h2>Створити новий пост</h2>
<h5>Загружайте файли формату PNG/JPEG </h5>

<%= form_for(@post) do |f| %>
<div class="field">


<div class="input-group">
  <span class="input-group-addon"><%= f.label "Назва" %></span>
  <%= f.text_field :title, class: "form-control" %>
</div>

<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title"> <%= f.label "Опис" %> </h3>
  </div>
  <div class="panel-body">
    <%= f.text_area :description, class: "form-control" %>
  </div>
</div>

<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title"> <%= f.label "Зображення" %> </h3>
  </div>
  <div class="panel-body">
    <%= f.file_field :content %>
  </div>
</div>
</div>
  <div class="actions">
    <%= f.submit "Створити", class: "btn btn-primary" %>
  </div>
<% end %>

</div>

app/views/posts/show.html.erb
<div class="content_all">
    <div class="row">
        <div class="col-md-2">
          <div class="rate">
            <button type="button" class="btn btn-default">Default</button>
            <button type="button" class="btn btn-default">Default</button>
          </div>
        </div>
        <div class="col-md-10">
              <div class="row">
                <div class="col-md-10">
                  <h3><%= @post.title%></h3>
                  <div class="post_description">
                    <h5><%= @post.description%></h5>
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-md-10">
                  <h4><%= image_tag("/users/" + @post.user_id.to_s + "/" + @post.content, :alt => "meme") %></h4>
                </div>
              </div>
        </div>
    </div>
    <% if current_user%>
    <div class="row">
    	<div class="col-md-12">
    		<div class="comment_new_panel">
            <%= render 'comment_new' %>
        </div>
    	</div>
    </div>
    <% else %>
	    <div class="comment_new_panel">
	        <div class="input-group">
	        	<div class="panel panel-default">
				  <div class="panel-heading">
				    <h3 class="panel-title">Увійдіть, щоб додати комментар</h3>
				  </div>
				  <div class="panel-body">
	                <a class="btn btn-primary" href="<%= login_path %>"> Увійти </a>
				  </div>
				</div>
	        </div>
	    </div>
    <% end %>
    <div class="comment_all">
	    <% @comments.each do |comment|%>
	        <div class="comment_row" style="margin-left:<%= comment.answer.to_i * 5 %>px">
			    <div class="row">
			        <div class="col-md-1">
			            <%= image_tag("/users/" + comment.user.id.to_s + "/" + comment.user.avatar, size: "50", 
                  :alt => "avatar") %>
			        </div>
			        <div class="col-md-10">
			              <div class="row">
			                <div class="col-md-10">
			                  <h4> <%= comment.user.login %> </h4>
			                  <div class="post_description">
			                    <h5><%= comment.content %></h5>
			                  </div>
			                </div>
			              </div>
			        </div>
			    </div>
		    </div>
	    <%end%>
   </div>
</div>
<div class="par">
  <h3 class="clh1">parent</h3>
</div>

app/views/user_sessions/_form.html.erb
<%= form_tag user_sessions_path, :method => :post do %>
  <div class="field">
    <%= label_tag :email %><br />
    <%= text_field_tag :email %>
  </div>
  <div class="field">
    <%= label_tag :password %><br />
    <%= password_field_tag :password %>
  </div>
  <div class="actions">
    <%= submit_tag "Login" %>
  </div>
<% end %>

app/views/user_sessions/create.html.erb
<h1>UserSessions#create</h1>
<p>Find me in app/views/user_sessions/create.html.erb</p>

app/views/user_sessions/destroy.html.erb
<h1>UserSessions#destroy</h1>
<p>Find me in app/views/user_sessions/destroy.html.erb</p>

app/views/user_sessions/new.html.erb
<div class="sign_form">
<div class="panel panel-info">
	<div class="panel-heading">
		<h3>Увійти<h3>
	</div>
	<div class="panel-body">
    <p><h5>Виповніть вхід через соціальну мережу</h5></p>
      <p>
         <button type="button" class="btn btn-primary btn-lg">Facebook</button>
         <button type="button" class="btn btn-success btn-lg">Vkontakte</button>
      </p>
	  <h5>Або авторизуйтесь за допомогою вашого email</h5>
      <p><%= render 'form' %></p>
  </div>
</div>
</div>

app/views/users/_flash.html.erb
<div class="options_flash">
    <% if flash[:success] %>
        <div class="alert alert-success"><%= flash[:success] %></div>
    <% elsif flash[:alert] %>
        <div class="alert alert-danger"><%= flash[:alert] %></div>
    <% end %>
</div>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :login %>
    <%= f.text_field :login %>
  </div>
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit %></div>
<% end %>

app/views/users/account.html.erb
<div class="settings_content">
    <div class="row">
        <div class="col-md-2 tabs-left">
            <ul class="nav nav-tabs tabs-left">
              <li class="active"><a href="<%= account_path%>">Аккаунт</a></li>
              <li><a href="<%= password_path%>">Пароль</a></li>
            </ul>
        </div>
        <div class="col-md-9">
            <div class="row">
                <p><%= render 'flash' %></p>
                <div class="col-md-9">
                    <h1 class="account_title">Аккаунт</h1>
                    <%= form_for @user, :url => update_names_path  do |f| %>
                        <div class="field">
                            <div class="panel panel-default">
                                <div class="panel-heading">
                                    <h3 class="panel-title"> <%= f.label "Аватар" %> </h3>
                                </div>
                                <div class="panel-body">
                                    <div class="avatar">
                                        <%= image_tag("/users/" + current_user.id.to_s + "/" + @user.avatar, 
                                        alt: "avatar") %>
                                    </div>
                                    <div class="avatar_new">
                                        <div>
                                            <%= f.file_field :avatar %>
                                        </div>
                                        <div>
                                            <h6>Загружайте файли формату PNG/JPEG</h6>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="input-group">
                                <span class="input-group-addon"><%= f.label "Email" %></span>
                                <%= f.text_field :email, class: "form-control" %>
                            </div>
                            <div class="input-group">
                                <span class="input-group-addon"><%= f.label "Логін" %></span>
                                <%= f.text_field :login, class: "form-control" %>
                            </div>
                            <div class="panel panel-default">
                                <div class="panel-heading">
                                    <h3 class="panel-title"> <%= f.label "Стать" %> </h3>
                                </div>
                                <div class="panel-body">
                                    <div class="col-md-4">
                                    <select class="form-control" id="user_gender" name="user[gender]">
                                     <% if @user.gender == "1" %>
                                        <option value="1" selected="selected">Чоловік</option>
                                        <option value="2">Жінка</option>
                                    <% else %>
                                        <option value="1">Чоловік</option>
                                        <option value="2" selected="selected">Жінка</option>
                                    <% end %>
                                    </select>
                                </div>
                                </div>
                            </div>
                        </div>
                        <div class="actions">
                            <%= f.submit "Змінити", class: "btn btn-primary" %>
                        </div>
                    <% end %>             
                </div>
            </div>
        </div>
    </div>
</div>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/index.html.erb
usesrs index

app/views/users/new.html.erb
<div class="sign_form">
<div class="panel panel-info">
	<div class="panel-heading">
		<h3>Реєстрація<h3>
	</div>
  <div class="panel-body">
    <p><h5>Зареєструйтесь через соціальну мережу</h5></p>
      <p>
         <button type="button" class="btn btn-primary btn-lg">Facebook</button>
         <button type="button" class="btn btn-success btn-lg">Vkontakte</button>
      </p>
    <h5>Або  за допомогою вашого email</h5>
      <p><%= render 'form' %></p>
  </div>
</div>
</div>

app/views/users/password.html.erb
   <div class="settings_content">
    <div class="row">
        <div class="col-md-2 tabs-left">
            <ul class="nav nav-tabs tabs-left">
			  <li><a href="<%= account_path%>">Аккаунт</a></li>
			  <li class="active"><a href="<%= password_path%>">Пароль</a></li>
			</ul>
        </div>
        <div class="col-md-9">
            <div class="row">
                <p><%= render 'flash' %></p>
                <div class="col-md-9">
                    <h1>Пароль</h1>
                    <h5>Довжина не менше 8 символів</h5>
                    <%= form_for @user, :url => update_password_path do |f| %>
                        <div class="field">
                            <div class="input-group">
                                <span class="input-group-addon"><%= f.label "Новий пароль" %></span>
                                <%= f.password_field :password, class: "form-control" %>
                            </div>
                            <div class="input-group">
                                <span class="input-group-addon"><%= f.label "Підтвердження" %></span>
                                <%= f.password_field :password_confirmation, class: "form-control" %>
                            </div>
                        </div>
                        <div class="actions">
                            <%= f.submit "Змінити", class: "btn btn-primary" %>
                        </div>
                    <% end %>             
                </div>
            </div>
        </div>
    </div>
</div>

app/views/users/profile.html.erb
<div class="content_all">
  <div class="profile_table">
    <div class="row">
      <div class="centre">
        <dl class="dl-horizontal">
          <dt>Логін</dt>
          <dd><%= @user.login%></dd>
          <dt>Карма</dt>
          <dd>...</dd>
          <dt>Постів</dt>
          <dd>....</dd>
          <dt>Коментарів</dt>
          <dd>...</dd>
        </dl>
      </div>
    </div>
    <hr>
    <hr>
  </div>
  <% @user.posts.each do |post| %>
    <div class="row">
        <div class="col-md-2">
          <div class="rate">
            <button type="button" class="btn btn-default">Default</button>
            <button type="button" class="btn btn-default">Default</button>
          </div>
        </div>
        <div class="col-md-10">
              <div class="row">
                <div class="col-md-10">
                  <h3><%= link_to post.title, post_path(post)%></h3>
                  <div class="post_description">
                    <h5><%= post.description%></h5>
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-md-10">
                  <h4><%= image_tag("/users/" + post.user_id.to_s + "/" + post.content, :alt => "meme") %></h4>
                </div>
              </div>
        </div>
    </div>
  <% end %>  
</div>